small changes

diff --git a/libg b/libg
--- a/libg
+++ b/libg
@@ -1,30 +1,26 @@
 #!/bin/sh
 
-DEFAULT_SEARCHBY=""
 DEFAULT_RESPERPAGE=100
 DEFAULT_DEPTH=1
-DEFAULT_SORTBY=""
-DEFAULT_SORTORDER=""
 
 basic_help() {
-	printf "libg: Shell Script to scrape library genesis website and download books right from the terminal.\n"
-	printf "USAGE: libg [OPTIONS] <search query>\n"
-	printf "  OPTIONS: Allowed values\n"
-	printf "\t-b <value>\t'Search By': author, title, publisher, year, isbn, language, md5, tags, extension.\n"
-	printf "\t-n <value>\t'Number of Search Results per Page': 25, 50, 100.\n"
-	printf "\t-d <value>\t'Depth'(Number of result pages to scan): Any positive integer.\n"
-	printf "\t-s <value>\t'Sort Results By': id, author, title, publisher, year, pages, language, filesize, extension.\n"
-	printf "\t-o <value>\t'Sort Order': ASC/asc (for ascending order), DESC/desc (for descending order).\n"
-	printf "\n  Current Defaults: (Can be changed by editing the script)\n"
-	printf "\t'Search By': $DEFAULT_SEARCHBY\n"
-	printf "\t'Number of Search Results per Page': $DEFAULT_RESPERPAGE\n"
-	printf "\t'Depth': $DEFAULT_DEPTH\n"
-	printf "\t'Sort Results By': $DEFAULT_SEARCHBY\n"
-	printf "\t'Sort Order': $DEFAULT_SORTORDER\n"
+	printf "libg: Shell Script to scrape library genesis website and download books right from the terminal.\
+	\nUSAGE: libg [OPTIONS] <search query>\
+	\n\nOPTIONS        Description                               Allowed Values\
+	\n-------        -----------                               --------------\
+	\n-b <value>     Search By                                 author, title, publisher, year, isbn, language, md5, tags, extension.\
+	\n-n <value>     Number of Search Results per Page         25, 50, 100.\
+	\n-d <value>     Depth (Number of result pages to scan)    Any positive integer.\
+	\n-s <value>     Sort Results By                           id, author, title, publisher, year, pages, language, filesize, extension.\
+	\n-r             Reverse/Desecending Order\
+	\n\nCurrent Defaults (Can be changed by editing the script)\
+	\n----------------\
+	\nNumber of Search Results per Page       $DEFAULT_RESPERPAGE\
+	\nDepth                                   $DEFAULT_DEPTH"
 }
 
 # -- PARSE OPTIONS --
-while getopts b:n:d:s:o:h opt; do
+while getopts b:n:d:s:rh opt; do
 	case "$opt" in
 		# SEARCHBY: author, title, publisher, year, isbn, language, md5, tags, extension
 		b) SEARCHBY="$OPTARG" ;;
@@ -35,7 +31,7 @@ while getopts b:n:d:s:o:h opt; do
 		# SORTBY: id, author, title, publisher, year, pages, language, filesize, extension
 		s) SORTBY="$OPTARG" ;;
 		# SORTORDER: ASC, DESC
-		o) SORTORDER="$OPTARG" ;;
+		r) SORTORDER=DESC ;;
 		h) basic_help && exit 0 ;;
 		\?) basic_help && exit 1 ;;
 	esac
@@ -44,7 +40,7 @@ shift $(( OPTIND-1 ))
 
 # -- CHECK VALIDITY OF OPTIONS --
 case "$SEARCHBY" in
-	"") SEARCHBY="$DEFAULT_SEARCHBY" ;; author) ;; title) ;; publisher) ;; year) ;; isbn) ;; language) ;; md5) ;; tags) ;; extension) ;;
+	"") ;; author) ;; title) ;; publisher) ;; year) ;; isbn) ;; language) ;; md5) ;; tags) ;; extension) ;;
 	*) printf "\033[31mERR\033[0m: Invalid Value for -b option!\nAllowed values: author, title, publisher, year, isbn, language, md5, tags, extension.\n" && exit 1 ;;
 esac
 
@@ -63,17 +59,17 @@ case "$DEPTH" in
 esac
 
 case "$SORTBY" in
-	"") SORTBY="$DEFAULT_SORTBY" ;; id) ;; author) ;; title) ;; publisher) ;; year) ;; pages) ;; language) ;; filesize) ;; extension) ;;
+	"") ;; id) ;; author) ;; title) ;; publisher) ;; year) ;; pages) ;; language) ;; filesize) ;; extension) ;;
 	*) printf "\033[31mERR\033[0m: Invalid Value for -s option!\nAllowed values: id, author, title, publisher, year, pages, language, filesize, extension.\n" && exit 1 ;;
 esac
 
 case "$SORTORDER" in
-	"") SORTORDER="$DEFAULT_SORTORDER" ;; ASC) ;; DESC) ;; asc) SORTORDER="ASC" ;; desc) SORTORDER="DESC" ;;
-	*) printf "\033[31mERR\033[0m: Invalid Value for -o option!\nAllowed values: ASC/asc for ascending order, DESC/desc for descending order.\n" && exit 1 ;;
+	"") ;; ASC) ;; DESC) ;;
+	*) printf "\033[31mERR\033[0m: Invalid value given for SORTORDER." && exit 1 ;;
 esac
 
+
 # -- GET SEARCH TERMS --
-rm -f /tmp/libgdata.file
 SEARCHTERM="$*"
 if [ -z "$SEARCHTERM" ]; then
 	printf "Enter searchterm: "
@@ -82,6 +78,8 @@ fi
 
 # -- SCRAPING --
 page=1
+original_page="$(mktemp)"
+data_file="$(mktemp)"
 while [ "$page" -le "$DEPTH" ]; do
 	printf "\033[1mGetting Page \033[35m$page... \033[0m"
 
@@ -91,24 +89,24 @@ while [ "$page" -le "$DEPTH" ]; do
 		--data-urlencode "res=$RESPERPAGE" \
 		--data-urlencode "page=$page" \
 		--data-urlencode "sort=$SORTBY" \
-		--data-urlencode "sortmode=$SORTORDER" > /tmp/x.html
+		--data-urlencode "sortmode=$SORTORDER" > "$original_page"
 	status="$?"
 	[ "$status" -eq 6 ] && printf "\033[31mFailed!\nERR\033[0m: Couldn't connect to Library Genesis! Check you internet connection and try again!\n" && exit 2
 
 	printf "\033[32mCompleted!\033[0m\n"
 	printf "\033[1mScraping Page \033[35m$page... \033[0m"
-	if grep -q '<td><b>Edit</b></td></tr></tr></table>' /tmp/x.html; then
+	if grep -q '<td><b>Edit</b></td></tr></tr></table>' "$original_page"; then
 		printf "\033[1mEnd of Results! Nothing on page \033[35m$page!\033[0m\n"
 		[ "$page" -eq 1 ] && exit
 		break
 	fi
 	# Extract the relevant part. Note that we are making only one pass through the file :)
-	sed -i -n '/^<td><b>Edit.*/,$p;/^<\/tr><\/table>$/q' /tmp/x.html
+	sed -i -n '/^<td><b>Edit.*/,$p;/^<\/tr><\/table>$/q' "$original_page"
 	# -- Cleaning up --
 	# Remove unnecessary part from first line and delete last line
-	sed -i '1s_.*<td_<td_;$d' /tmp/x.html
+	sed -i '1s_.*<td_<td_;$d' "$original_page"
 	# Delete lines of closing </tr> tags
-	sed '/^\t*<\/tr>$\|^$/d' /tmp/x.html |\
+	sed '/^\t*<\/tr>$\|^$/d' "$original_page" |\
 	# Remove opening <td> and closing </td> tags along with \r's
 	sed 's_\t*</\?td[^>]*>\r\?__g' |\
 	# -- Extracting authors --
@@ -135,15 +133,15 @@ while [ "$page" -le "$DEPTH" ]; do
 	tr '\n' '\t' | sed 's_<tr[^>]*>_\n_g' | sed 's_\s*$__' |\
 	# -- Moving Series and ISBNs to last --
 	sed 's_\(\t\x01[^\t]*\)\?\(\t\x02[^\t]*\)\(\t\x03[^\t]*\)\?\(.*\)_\2\4\t\1\3_' |\
-	sed 's_\t\x01_\x01_' >> /tmp/libgdata.file
-	printf "\n" >> /tmp/libgdata.file
+	sed 's_\t\x01_\x01_' >> "$data_file"
+	printf "\n" >> "$data_file"
 	printf "\033[32mCompleted!\033[0m\n"
-	page=$(( page+1 ))
+	page=$((page+1))
 done
 
 # -- DISPLAYING IN FZF --
 # ID, Author, Title, Publisher, Year, Pages, Language, Size, Extension, Links, [Series], [ISBNs] -> 1,2,3,4,5,6,7,8,9,10,11,12
-id=$(awk -F "\t" '{printf("%-30.30s | %-70.70s | %-16.16s | %-7.7s | %-4.4s | %-s\n", $2, $3, $5, $8, $9, $1)}' /tmp/libgdata.file |\
+id=$(awk -F "\t" '{printf("%-30.30s | %-70.70s | %-16.16s | %-7.7s | %-4.4s | %-s\n", $2, $3, $5, $8, $9, $1)}' "$data_file" |\
 	fzf  --ansi --preview 'awk -F"\t" '\''$1 == '\''{-1}'\'' \
 	{printf("\033[1m\033[31mID:\033[0m %s\
 		\n\033[1m\033[31mAuthors:\033[0m %s\
@@ -155,14 +153,15 @@ id=$(awk -F "\t" '{printf("%-30.30s | %-70.70s | %-16.16s | %-7.7s | %-4.4s | %-
 		\n\033[1m\033[31mPages:\033[0m %s\
 		\n\033[1m\033[31mLanguage:\033[0m %s\
 		\n\033[1m\033[31mSize:\033[0m %s\
-		\n\033[1m\033[31mExtension:\033[0m %s", $1,$2,$3,$11,$12,$4,$5,$6,$7,$8,$9)}'\'' /tmp/libgdata.file'\
-	--preview-window=up:35% |\
+		\n\033[1m\033[31mExtension:\033[0m %s", $1,$2,$3,$11,$12,$4,$5,$6,$7,$8,$9)}'\'' '"$data_file"''\
+	--no-sort --preview-window=up:35% |\
 	awk '{print $NF}')
 [ -z "$id" ] && exit 0;
 
 # -- DOWNLOADING --
-firstlink=$(awk -F"\t" '$1=="'"$id"'" {print $10}' /tmp/libgdata.file | awk '{print $1}')
-curl -s "$firstlink" > /tmp/y.html
-DOWNLOAD_URL=$(grep '<h2><a href=[^>]*>GET</a></h2>' /tmp/y.html | sed 's_<h2><a href=["'\'']\(.*\)["'\'']>GET</a></h2>_\1_')
+download_page="$(mktemp)"
+firstlink=$(awk -F"\t" '$1=="'"$id"'" {print $10}' "$data_file" | awk '{print $1}')
+curl -s "$firstlink" > "$download_page"
+DOWNLOAD_URL=$(grep '<h2><a href=[^>]*>GET</a></h2>' "$download_page" | sed 's_<h2><a href=["'\'']\(.*\)["'\'']>GET</a></h2>_\1_')
 wget $DOWNLOAD_URL
-rm -f /tmp/x.html /tmp/y.html
+rm -f "$original_page" "$data_file" "$download_page"
